layout_spectrum: 0.2593068
typography_spectrum: 0.8417477
color:
  saturation: 0.5342463
  lightness: 0.1890677
  brandStrength: 0.9703907
  rhythmicContrast: 0.474947
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Art Ramen
